### ISSUE TITLE
Attribute Table Filter And Sync Map issues

### ISSUE THREAD

**Issue by Dukestep** [geosolutions-it/geonode-mapstore-client#140]
I have noticed an issue in both my own dev instance of Geonode/Mapstore and the one available at [dev.geonode.geo-solutions.it](url) with the attribute table filter and the "Sync map with filter" attribute table tool. When filtering on a string attribute in the attribute table and activating the sync button, multiple requests are sent and each returns the following error:

`Rendering process failed
java.io.IOExceptionjava.lang.String cannot be cast to org.opengis.feature.type.AttributeDescriptor`

### Steps to reproduce

1. URL: http://dev.geonode.geo-solutions.it/maps/new?layer=geonode:ne_10m_roads&view=True#/
2. Open the attribute table, filter the "level" attribute on value "Interstate"
3. See response received from individual requests made to the Geoserver.

I tried looking if this issue was already flagged but did not see any related issues.

**Comment by giohappy** [comment]
@Dukestep sorry for the very late reply but we still haven't officially released the client so we have not put in place the resources to manage public issues. We will do it as soon as this repository will be published under the GeoNode repos.
Anyway the issue you report is due to a problem with CQL function encoding. It can be circumvented disabling the "encode filters" flag under the specific PostGIS store configuratiion. See image below.

![image](https://user-images.githubusercontent.com/571129/54202077-857d2100-44cf-11e9-8a6b-1a1cba8f82c3.png)
