### ISSUE TITLE
Remove temporary styles from Geoserver

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode-mapstore-client#155]
In case the Style Editor window is not properly closed, temprary styles aren't removed from Geoserver and they will appear in GeoNode.
Temp styles can be detected from their name pattern (@allyoucanmap please provide the pattern)

Option 1 (preferred)
Use some layer signal to trigger the removal of temporary styles

Option2
Filter temporary styles and hide them (this doesn't clean the trash and probably require adding a queryset filter inside geonode core)

**Comment by allyoucanmap** [comment]
temporary styles

example
0d11aa20-17e2-11e9-a229-9f0f3427f1eb_ms_1547459526082

structure
**uuid**`_ms_`**date**

**Comment by simboss** [comment]
This is somewhat related to #87

**Comment by simboss** [comment]
@giohappy I would ask alessio to put in place a temporary fix for the time being  (Option 2) then ew revisit this issue with having a mind a better solution that does not force us to create temp files on disk on GeoServer.

This might involve a separate endpoint for auhtenticated users where mapstore place transient style and Gs pull them from there, or the concept of tempo style in GeoServer which is not persisted to disk.
Having in mind a distributed environment it would be best to have temp styles outside GeoServer so that are shared easily but we can discuss.

**Comment by giohappy** [comment]
ok @simboss 
I agree that we need a proper solution in the long term. The initial idea was to give MS and endpoint to store temp style and pass them to GS with SLD_URL / SLD_BODY params, but it requires GS to support CSS styles from remote resources.

Meanwhile ok, let's add an hardcoded rule to hide temp files based on their name...
@afabiani give it a look and prepare an estimate.

**Comment by afabiani** [comment]
Temporary fix (solution 2)

https://github.com/geosolutions-it/geonode/commit/edc231d353fe715cb1a57eae0630d08d53641db2#diff-573fe814430356516f7ac7c14703b9acR217
