### ISSUE TITLE
Identify options did not work on Map Editor Inline (GeoStory)

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/geonode-mapstore-client#209]
Identify types (`HTML`,  `TEXT`, `PROPERTIES`) cannot be selected from the inline Map Editor on GeoStory.
![fffff](https://user-images.githubusercontent.com/56537133/107789111-7b19d080-6d51-11eb-9776-ae94d1cbe15a.png)

**How to Reproduce**
- Open [this geostory](https://master.demo.geonode.org/apps/425/edit#/) on master.demo
- From a map content, click on Edit Map Configuration
- On Settings, change the Identify types 

*Current Result*
It is not possible to change the identify through `HTML`,  `TEXT` and `PROPERTIES` options

**Comment by luorlandini** [comment]
Hi @ElenaGallo I tested 2 cases

the first with default attributes, in this case is possibile to change the identify through HTML, TEXT and PROPERTIES
as you can see in the video 


https://user-images.githubusercontent.com/4085786/110798711-bb01a400-827a-11eb-96b6-d3cd9b636f07.mov

the second with the custom attributes template, in this case the identify doesn't change, maybe the behavior is right, 
because the custom template override the generic one set at the map level

https://user-images.githubusercontent.com/4085786/110799163-29defd00-827b-11eb-9c37-d3453972dbda.mov

**Comment by ElenaGallo** [comment]
@luorlandini you are right. I have tried with the custom attributes template. @giohappy what do you think, is it not a problem if the attributes template is customized?

**Comment by giohappy** [comment]
@ElenaGallo I would close this since this we're not facing an error. We might open a feature request to improve the UX, but this is the way it is expected to work now.
