### ISSUE TITLE
Printing plugin zoom/scale issues

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode-mapstore-client#63]
Currently the outcome does not match the preview panel

**Comment by giohappy** [comment]
Please provide some reproducible cases. From my tests it works fine

**Comment by giohappy** [comment]
@afabiani can you give the sequence and related outcomes to understand and reproduce the issue?

**Comment by gioscarda** [comment]
The problem is not specifically related to the MS2 integration.
It could be due to the geoserver printing configuration (see config.yaml).

The following is an example:
- preview
![Selection_029](https://user-images.githubusercontent.com/43670920/54446713-e151df00-4747-11e9-897e-68982c661fd3.png)
- outcome
![Selection_030](https://user-images.githubusercontent.com/43670920/54446730-ea42b080-4747-11e9-9e27-1a01ff558f6c.png)

**Comment by giohappy** [comment]
ok @gioscarda dig into this and see what' the problem (if there's any) with the config.yaml

**Comment by gioscarda** [comment]
It is not a bug.
This is a `scale` problem due to the configuration of mapstore base plugins.
In `ms2_base_plugins.js`, the `MS2_BASE_PLUGINS`  variable contains this setting:

```
"name": "Print",
"cfg": {
        "useFixedScales": true
}
```
So the scale shown in the print preview is not considered in the final result.

@afabiani and @giohappy, do I change this settings?
