### ISSUE TITLE
Management of GWC Cached Layers

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode-mapstore-client#64]
GeoNode should expose endpoints to empty/truncate GWC cache.

MapStore2 should be able to invoke above endpoints whenever some change occurs on features or SLD

**Comment by afabiani** [comment]
Check GeoServer Transaction Listener

**Comment by simboss** [comment]
As far as doing edits via WFS-T is concerned there should be a transaction listener to do handles this.
If it does not work let's check why and fix GeoServer rather than creating more code around it.

As far as SLD saving it should be the same, there should be a cataloglistener that does the same.
I don't remember if this is already there or not; if not the path is creating such a listener rather than adding code around GeoServer.

**Comment by simboss** [comment]
I have turned this into a users story.

We need to create two tasks for the two  issues mentioned in this one and investigate accordingly.

**Comment by giohappy** [comment]
@afabiani this issue is still pending and I was able to reproduce it with, fo instance, http://dev.geonode.geo-solutions.it/layers/geonode:punti.

**Comment by afabiani** [comment]
Moved to https://github.com/GeoNode/geonode-mapstore-client/issues/13
